"""Add created_at to settlements

Revision ID: 24417ff15934
Revises: 001_restructure_add_fields
Create Date: 2025-10-18 22:47:04.076400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '24417ff15934'
down_revision: Union[str, Sequence[str], None] = '001_restructure_add_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def column_exists(table_name, column_name):
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c["name"] for c in inspector.get_columns(table_name)]
    return column_name in columns

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_expenses_owner_id'), 'expenses', ['owner_id'], unique=False)
    op.drop_column('expenses', 'timestamp')
    op.alter_column('group_expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_group_expenses_group_id'), 'group_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_expenses_paid_by_id'), 'group_expenses', ['paid_by_id'], unique=False)
    if column_exists('group_expenses', 'paid_by_username'):
        op.drop_column('group_expenses', 'paid_by_username')
    try:
        op.alter_column(
            'group_members',
            'role',
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'member'::character varying")
        )
    except:
        pass
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.add_column('settlements', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_settlements_from_user_id'), 'settlements', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_index(op.f('ix_settlements_to_user_id'), 'settlements', ['to_user_id'], unique=False)
    op.drop_column('settlements', 'to_username')
    op.drop_column('settlements', 'from_username')
    op.drop_column('settlements', 'timestamp')
    op.create_index(op.f('ix_splits_group_expense_id'), 'splits', ['group_expense_id'], unique=False)
    op.create_index(op.f('ix_splits_user_id'), 'splits', ['user_id'], unique=False)
    if column_exists('splits', 'paid_by_username'):
        op.drop_column('splits', 'paid_by_username')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_username'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['upi_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('splits', sa.Column('paid_by_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_splits_user_id'), table_name='splits')
    op.drop_index(op.f('ix_splits_group_expense_id'), table_name='splits')
    op.add_column('settlements', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('settlements', sa.Column('from_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settlements', sa.Column('to_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_settlements_to_user_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_from_user_id'), table_name='settlements')
    op.drop_column('settlements', 'created_at')
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.alter_column('groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    try:
        op.alter_column(
            'group_members',
            'role',
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'member'::character varying")
        )
    except:
        pass
    op.add_column('group_expenses', sa.Column('paid_by_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_group_expenses_paid_by_id'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_group_id'), table_name='group_expenses')
    op.alter_column('group_expenses', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('expenses', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_expenses_owner_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_group_id'), table_name='expenses')
    op.alter_column('expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
