"""add UPI columns and settlement updates

Revision ID: 5855f7f5bd86
Revises: e931604936a4
Create Date: 2025-09-05 17:10:48.721701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5855f7f5bd86'
down_revision: Union[str, Sequence[str], None] = 'e931604936a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('proof_url', sa.String(), nullable=True))
    op.add_column('settlements', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'status')
    op.drop_column('settlements', 'proof_url')
    # ### end Alembic commands ###
