"""add username to users

Revision ID: b2c745b97099
Revises: 9bd943a2540b
Create Date: 2025-08-01 10:33:20.524244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c745b97099'
down_revision: Union[str, Sequence[str], None] = '9bd943a2540b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add the column as nullable
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))

    # Step 2: Fill in username using part of email
    op.execute("UPDATE users SET username = split_part(email, '@', 1)")

    # Step 3: Now safely make it NOT NULL
    op.alter_column('users', 'username', nullable=False)

    # Step 4: Add uniqueness constraint
    op.create_unique_constraint('uq_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
