"""add upi fields to users

Revision ID: e931604936a4
Revises: b2c745b97099
Create Date: 2025-09-04 15:09:14.550607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e931604936a4'
down_revision: Union[str, Sequence[str], None] = 'b2c745b97099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_group_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('group_expenses', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_expenses', 'paid_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('group_expenses_group_id_fkey'), 'group_expenses', type_='foreignkey')
    op.drop_constraint(op.f('group_expenses_paid_by_id_fkey'), 'group_expenses', type_='foreignkey')
    op.create_foreign_key(None, 'group_expenses', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_expenses', 'users', ['paid_by_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('group_members_group_id_fkey'), 'group_members', type_='foreignkey')
    op.drop_constraint(op.f('group_members_user_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('groups_owner_id_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('settlements', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settlements', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settlements', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('settlements', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('settlements_group_id_fkey'), 'settlements', type_='foreignkey')
    op.drop_constraint(op.f('settlements_from_user_id_fkey'), 'settlements', type_='foreignkey')
    op.drop_constraint(op.f('settlements_to_user_id_fkey'), 'settlements', type_='foreignkey')
    op.create_foreign_key(None, 'settlements', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'settlements', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'settlements', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('splits', 'group_expense_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('splits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('splits', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('splits_user_id_fkey'), 'splits', type_='foreignkey')
    op.drop_constraint(op.f('splits_group_expense_id_fkey'), 'splits', type_='foreignkey')
    op.create_foreign_key(None, 'splits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'splits', 'group_expenses', ['group_expense_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('upi_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('upi_verified', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'upi_verified')
    op.drop_column('users', 'upi_id')
    op.drop_constraint(None, 'splits', type_='foreignkey')
    op.drop_constraint(None, 'splits', type_='foreignkey')
    op.create_foreign_key(op.f('splits_group_expense_id_fkey'), 'splits', 'group_expenses', ['group_expense_id'], ['id'])
    op.create_foreign_key(op.f('splits_user_id_fkey'), 'splits', 'users', ['user_id'], ['id'])
    op.alter_column('splits', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('splits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('splits', 'group_expense_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.drop_constraint(None, 'settlements', type_='foreignkey')
    op.create_foreign_key(op.f('settlements_to_user_id_fkey'), 'settlements', 'users', ['to_user_id'], ['id'])
    op.create_foreign_key(op.f('settlements_from_user_id_fkey'), 'settlements', 'users', ['from_user_id'], ['id'])
    op.create_foreign_key(op.f('settlements_group_id_fkey'), 'settlements', 'groups', ['group_id'], ['id'])
    op.alter_column('settlements', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('settlements', 'to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settlements', 'from_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('settlements', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_owner_id_fkey'), 'groups', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_user_id_fkey'), 'group_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'group_expenses', type_='foreignkey')
    op.drop_constraint(None, 'group_expenses', type_='foreignkey')
    op.create_foreign_key(op.f('group_expenses_paid_by_id_fkey'), 'group_expenses', 'users', ['paid_by_id'], ['id'])
    op.create_foreign_key(op.f('group_expenses_group_id_fkey'), 'group_expenses', 'groups', ['group_id'], ['id'])
    op.alter_column('group_expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('group_expenses', 'paid_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_expenses', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_group_id_fkey'), 'expenses', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
